# Generated by Django 5.0.1 on 2024-01-20 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_passengerprofile_user_delete_adminprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passengerprofile',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
