# Generated by Django 5.0.1 on 2024-01-21 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactus',
            old_name='tel',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='contactus',
            old_name='problem',
            new_name='message',
        ),
        migrations.AddField(
            model_name='contactus',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
