# Generated by Django 5.0.1 on 2024-01-18 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passenger', '0002_alter_passenger_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passenger',
            name='balance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
