# Generated by Django 5.0.1 on 2024-01-20 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_type', models.CharField(blank=True, choices=[('Economy', 'Economy'), ('FirstClass', 'First Class'), ('Business', 'Business'), ('Premium', 'Premium'), ('Luxury', 'Luxury')], max_length=50, null=True)),
                ('seats_booked', models.IntegerField()),
                ('selected_seat', models.CharField(blank=True, max_length=100, null=True)),
                ('booking_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
