# Generated by Django 5.0.1 on 2024-01-20 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('train', '0002_trainreview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='train',
            name='train_type',
        ),
    ]
