# Generated by Django 5.0.1 on 2024-01-20 19:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_passengerprofile_balance'),
        ('train', '0003_alter_trainreview_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainreview',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='train_review', to='account.passengerprofile'),
        ),
    ]
