# Generated by Django 5.0.1 on 2024-01-20 17:59

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0003_alter_passengerprofile_balance'),
        ('train', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.passengerprofile')),
                ('train', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_tickets', to='train.train')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_type', models.CharField(choices=[('Economy', 'Economy'), ('FirstClass', 'First Class'), ('Business', 'Business'), ('Premium', 'Premium'), ('Luxury', 'Luxury')], max_length=50)),
                ('seats_quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('selected_seat', models.CharField(choices=[('A1', 'A1'), ('A2', 'A2'), ('A3', 'A3'), ('A4', 'A4'), ('A5', 'A5'), ('A6', 'A6'), ('A7', 'A7'), ('A8', 'A8'), ('A9', 'A9'), ('A10', 'A10'), ('A11', 'A11'), ('A12', 'A12'), ('A13', 'A13'), ('A14', 'A14'), ('A15', 'A15'), ('A16', 'A16'), ('A17', 'A17'), ('A18', 'A18'), ('A19', 'A19'), ('A20', 'A20'), ('A21', 'A21'), ('A22', 'A22'), ('A23', 'A23'), ('A24', 'A24'), ('A25', 'A25'), ('A26', 'A26'), ('A27', 'A27'), ('A28', 'A28'), ('A29', 'A29'), ('A30', 'A30'), ('A31', 'A31'), ('A32', 'A32'), ('A33', 'A33'), ('A34', 'A34'), ('A35', 'A35'), ('A36', 'A36'), ('A37', 'A37'), ('A38', 'A38'), ('A39', 'A39'), ('A40', 'A40'), ('A41', 'A41'), ('A42', 'A42'), ('A43', 'A43'), ('A44', 'A44'), ('A45', 'A45'), ('A46', 'A46'), ('A47', 'A47'), ('A48', 'A48'), ('A49', 'A49'), ('A50', 'A50')], max_length=100)),
                ('booking_date', models.DateTimeField(auto_now_add=True)),
                ('from_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_station', to='train.station')),
                ('to_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_station', to='train.station')),
                ('train', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='train.train')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-booking_date'],
            },
        ),
    ]
