# Generated by Django 5.0.1 on 2024-01-20 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderTicket',
        ),
    ]
