# Generated by Django 5.0.1 on 2024-01-20 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0002_delete_orderticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='selected_seat',
            field=models.CharField(max_length=100),
        ),
    ]
