# Generated by Django 5.0.1 on 2024-01-20 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0003_alter_ticket_selected_seat'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='ticket_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='ticket',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
